name: VirusTotal Scan

on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan files
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./Set-VirusScan/Set-VirusScan.ps1
            ./Set-VirusRescan/Set-VirusRescan.ps1
            ./Get-VirusReport/Get-VirusReport.ps1
            ./Get-VirusIPReport/Get-VirusIPReport.ps1
            ./Get-VirusDomainReport/Get-VirusDomainReport.ps1
